package enums;

public enum Profissao {
    RECURSOS_HUMANOS,
    ENGENHARIA_MECANICA,
    ENGENHARIA_ELETRICA,
    ENGENHARIA_AGRICOLA,
    AGENTE_DE_LIMPEZA,
    ADVOGADO,
    COMUNISTA,
    JARDINEIRO,
    MOTORISTA,
    TECNOLOGIA_DE_INFORMACAO;
}
